# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('crop_id', models.AutoField(primary_key=True, serialize=False)),
                ('local_name', models.CharField(max_length=100, null=True)),
                ('english_name', models.CharField(max_length=100, null=True)),
                ('scientific_name', models.CharField(max_length=100)),
                ('shelf_life', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Crop')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('date_of_manufacture', models.DateTimeField()),
                ('version', models.CharField(max_length=20)),
                ('last_login', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('date_of_produce', models.DateTimeField()),
                ('date_of_expiry', models.DateTimeField()),
                ('status', models.FloatField()),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Crop')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Trough',
            fields=[
                ('trough_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=20)),
                ('user_type', models.CharField(max_length=20)),
                ('contact', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='producer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.User'),
        ),
        migrations.AddField(
            model_name='produce',
            name='trough_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Trough'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Producer', to='farmapp.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Consumer', to='farmapp.User'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='crop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Crop'),
        ),
    ]
