# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'cart sessions',
            },
        ),
        migrations.RemoveField(
            model_name='producer',
            name='machine_id',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='user_id',
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'cart'},
        ),
        migrations.AlterModelOptions(
            name='crop',
            options={'verbose_name_plural': 'crops'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'inventories'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name_plural': 'machines'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='produce',
            options={'verbose_name_plural': 'produce'},
        ),
        migrations.AlterModelOptions(
            name='trough',
            options={'verbose_name_plural': 'troughs'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='crop_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='time',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='weight',
        ),
        migrations.AddField(
            model_name='crop',
            name='availability',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='crop',
            name='imagepath',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='short_name',
            field=models.CharField(default='Unknown', max_length=11),
        ),
        migrations.AddField(
            model_name='inventory',
            name='maximum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='minimum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sold',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmapp.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='crop_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='farmapp.Crop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmapp.Cart'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='scientific_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
        migrations.AddField(
            model_name='cart_session',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Cart'),
        ),
        migrations.AddField(
            model_name='cart_session',
            name='crop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Crop'),
        ),
    ]
