# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='machine_id',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='user_id',
        ),
        migrations.AddField(
            model_name='machine',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmapp.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
    ]
