# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produce',
            name='status',
        ),
        migrations.AddField(
            model_name='produce',
            name='sold',
            field=models.FloatField(default=0),
        ),
    ]
