# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0002_auto_20170604_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='scientific_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
