# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('farmapp', '0003_auto_20170619_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='maximum',
            field=models.FloatField(default=600),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='minimum',
            field=models.FloatField(default=50),
        ),
    ]
