# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0003_auto_20170605_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='imagepath',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
