# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('farmapp', '0005_auto_20170623_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='shelf_life',
            field=models.IntegerField(default=48),
        ),
        migrations.AddField(
            model_name='inventory',
            name='wasted',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='produce',
            name='wasted',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='crop',
            name='shelf_life',
            field=models.IntegerField(default=48),
        ),
    ]
