# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0005_auto_20170607_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='availabilty',
            field=models.FloatField(default=0),
        ),
    ]
