# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0005_auto_20170628_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trough',
            name='machine_id',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='trough_id',
        ),
        migrations.AddField(
            model_name='produce',
            name='farm_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Trough',
        ),
    ]
