# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0006_crop_availabilty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='availabilty',
            new_name='availability',
        ),
    ]
