# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0006_auto_20170628_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
