# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 10:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0007_auto_20170607_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_session',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 15, 30, 54, 645816)),
        ),
        migrations.AlterField(
            model_name='cart_session',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
