# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0008_auto_20170630_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
