# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 09:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0008_auto_20170608_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='short_name',
            field=models.CharField(default='Unknown', max_length=11),
        ),
        migrations.AlterField(
            model_name='cart_session',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 12, 15, 12, 18, 24641)),
        ),
    ]
