# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 10:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0009_auto_20170612_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmapp.Cart'),
        ),
        migrations.AlterField(
            model_name='cart_session',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 12, 15, 43, 16, 644175)),
        ),
    ]
