# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0010_auto_20170630_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prev_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
