# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 04:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0010_auto_20170612_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.FloatField(default=0)),
                ('maximum', models.FloatField(default=0)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Crop')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart_session',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart_id',
        ),
        migrations.AddField(
            model_name='order',
            name='crop_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmapp.Crop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart_session',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 13, 10, 15, 51, 561114)),
        ),
    ]
