# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 04:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0011_auto_20170613_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_id',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='farmapp.Cart_session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart_session',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 13, 10, 19, 14, 963341)),
        ),
    ]
