# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0011_user_prev_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prev_login',
        ),
    ]
