# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0012_remove_user_prev_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
