# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 10:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0013_auto_20170613_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_session',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 13, 16, 23, 49, 977765)),
        ),
    ]
