# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 07:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0014_auto_20170613_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='sold',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart_session',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 14, 13, 8, 55, 366779)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
    ]
