# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 08:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0015_auto_20170614_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_session',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 14, 13, 36, 3, 435509)),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.Cart'),
        ),
    ]
