# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 05:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0016_auto_20170614_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_session',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 11, 0, 5, 611073)),
        ),
    ]
