# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0017_auto_20170615_1100'),
        ('farmapp', '0017_auto_20170615_1103'),
    ]

    operations = [
    ]
