# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0018_merge_20170615_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_session',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
