# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0018_merge_20170615_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_session',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmapp.Cart'),
        ),
    ]
