# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0019_auto_20170615_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_session',
            name='time',
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
