# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0021_auto_20170615_1149'),
        ('farmapp', '0019_auto_20170615_1113'),
    ]

    operations = [
    ]
