# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0022_merge_20170616_1521'),
        ('farmapp', '0022_merge_20170616_1520'),
    ]

    operations = [
    ]
